"""Guardrails: pre-execution, pre-commit, pre-push, post-push quality gates."""

from __future__ import annotations

# Re-export post_push public API so "from guardrails import PostPushPipeline" works.
from .post_push import (
    AuditResult,
    BaselineSynthesis,
    CleanupResult,
    CommandValidationAdapter,
    DeepValidationResult,
    FileBackedDedupeStore,
    FileArtifactStore,
    Finding,
    FindingScores,
    InMemoryDedupeStore,
    MergeDecisionFinding,
    MergeDecisionHardGate,
    MergeDecisionResult,
    MergeDecisionSummary,
    ManagedSafeCleanup,
    MutationMode,
    NoopAuditAgent,
    PassValidation,
    PipelineConfig,
    PostPushContext,
    PostPushOutcome,
    PostPushPipeline,
    RepoIntrospectionSynthesis,
    RuleBasedMergeDecisionTriage,
    SafeNoopCleanup,
    Severity,
    StrandsAdversarialAgent,
    StrandsOptimizationAgent,
    StrandsReviewerAgent,
    StageStatus,
    SynthesisResult,
    TicketPayload,
    ValidationCheck,
    WorkItemIdentity,
)

__all__ = [
    "AuditResult",
    "BaselineSynthesis",
    "CleanupResult",
    "CommandValidationAdapter",
    "DeepValidationResult",
    "FileBackedDedupeStore",
    "FileArtifactStore",
    "Finding",
    "FindingScores",
    "InMemoryDedupeStore",
    "MergeDecisionFinding",
    "MergeDecisionHardGate",
    "MergeDecisionResult",
    "MergeDecisionSummary",
    "ManagedSafeCleanup",
    "MutationMode",
    "NoopAuditAgent",
    "PassValidation",
    "PipelineConfig",
    "PostPushContext",
    "PostPushOutcome",
    "PostPushPipeline",
    "RepoIntrospectionSynthesis",
    "RuleBasedMergeDecisionTriage",
    "SafeNoopCleanup",
    "Severity",
    "StrandsAdversarialAgent",
    "StrandsOptimizationAgent",
    "StrandsReviewerAgent",
    "StageStatus",
    "SynthesisResult",
    "TicketPayload",
    "ValidationCheck",
    "WorkItemIdentity",
]
